// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace StudentCURD.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Core.Entities.ClassTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 2, 26, 14, 32, 38, 973, DateTimeKind.Local).AddTicks(4583),
                            ModificationDate = new DateTime(2024, 2, 26, 14, 32, 38, 973, DateTimeKind.Local).AddTicks(4584),
                            Name = "One"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 2, 26, 14, 32, 38, 973, DateTimeKind.Local).AddTicks(4586),
                            ModificationDate = new DateTime(2024, 2, 26, 14, 32, 38, 973, DateTimeKind.Local).AddTicks(4586),
                            Name = "Two"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 2, 26, 14, 32, 38, 973, DateTimeKind.Local).AddTicks(4588),
                            ModificationDate = new DateTime(2024, 2, 26, 14, 32, 38, 973, DateTimeKind.Local).AddTicks(4588),
                            Name = "Three"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 2, 26, 14, 32, 38, 973, DateTimeKind.Local).AddTicks(4589),
                            ModificationDate = new DateTime(2024, 2, 26, 14, 32, 38, 973, DateTimeKind.Local).AddTicks(4590),
                            Name = "Four"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 2, 26, 14, 32, 38, 973, DateTimeKind.Local).AddTicks(4591),
                            ModificationDate = new DateTime(2024, 2, 26, 14, 32, 38, 973, DateTimeKind.Local).AddTicks(4591),
                            Name = "Five"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 2, 26, 14, 32, 38, 973, DateTimeKind.Local).AddTicks(4593),
                            ModificationDate = new DateTime(2024, 2, 26, 14, 32, 38, 973, DateTimeKind.Local).AddTicks(4593),
                            Name = "Six"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 2, 26, 14, 32, 38, 973, DateTimeKind.Local).AddTicks(4594),
                            ModificationDate = new DateTime(2024, 2, 26, 14, 32, 38, 973, DateTimeKind.Local).AddTicks(4595),
                            Name = "Seven"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 2, 26, 14, 32, 38, 973, DateTimeKind.Local).AddTicks(4596),
                            ModificationDate = new DateTime(2024, 2, 26, 14, 32, 38, 973, DateTimeKind.Local).AddTicks(4596),
                            Name = "Eight"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 2, 26, 14, 32, 38, 973, DateTimeKind.Local).AddTicks(4598),
                            ModificationDate = new DateTime(2024, 2, 26, 14, 32, 38, 973, DateTimeKind.Local).AddTicks(4598),
                            Name = "Nine"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 2, 26, 14, 32, 38, 973, DateTimeKind.Local).AddTicks(4599),
                            ModificationDate = new DateTime(2024, 2, 26, 14, 32, 38, 973, DateTimeKind.Local).AddTicks(4600),
                            Name = "Ten"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2024, 2, 26, 14, 32, 38, 973, DateTimeKind.Local).AddTicks(4601),
                            ModificationDate = new DateTime(2024, 2, 26, 14, 32, 38, 973, DateTimeKind.Local).AddTicks(4601),
                            Name = "Colleage First Year"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2024, 2, 26, 14, 32, 38, 973, DateTimeKind.Local).AddTicks(4640),
                            ModificationDate = new DateTime(2024, 2, 26, 14, 32, 38, 973, DateTimeKind.Local).AddTicks(4640),
                            Name = "Colleg Second Year"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2024, 2, 26, 14, 32, 38, 973, DateTimeKind.Local).AddTicks(4642),
                            ModificationDate = new DateTime(2024, 2, 26, 14, 32, 38, 973, DateTimeKind.Local).AddTicks(4642),
                            Name = "BSc In CSE"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2024, 2, 26, 14, 32, 38, 973, DateTimeKind.Local).AddTicks(4644),
                            ModificationDate = new DateTime(2024, 2, 26, 14, 32, 38, 973, DateTimeKind.Local).AddTicks(4644),
                            Name = "BSc In EEE"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2024, 2, 26, 14, 32, 38, 973, DateTimeKind.Local).AddTicks(4645),
                            ModificationDate = new DateTime(2024, 2, 26, 14, 32, 38, 973, DateTimeKind.Local).AddTicks(4646),
                            Name = "BSc In CS"
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2024, 2, 26, 14, 32, 38, 973, DateTimeKind.Local).AddTicks(4647),
                            ModificationDate = new DateTime(2024, 2, 26, 14, 32, 38, 973, DateTimeKind.Local).AddTicks(4647),
                            Name = "BSc In Civil"
                        });
                });

            modelBuilder.Entity("Core.Entities.StudentTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Core.Entities.StudentTable", b =>
                {
                    b.HasOne("Core.Entities.ClassTable", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("Core.Entities.ClassTable", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
