// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240903035846_userRoles")]
    partial class userRoles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Core.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "27076d17-0839-409d-8747-d078050c83ea",
                            AccessFailedCount = 0,
                            Address = "",
                            ConcurrencyStamp = "433d47ad-7d5a-49f2-9f27-2529eeb45660",
                            CreatedAt = new DateTime(2024, 9, 3, 9, 58, 46, 464, DateTimeKind.Local).AddTicks(8406),
                            Email = "habibor.rahaman1010@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Habibor",
                            LastName = "Rahaman",
                            LockoutEnabled = false,
                            NormalizedEmail = "HABIBOR.RAHAMAN1010@GMAIL.COM",
                            NormalizedUserName = "HABIBOR.RAHAMAN1010@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEEsm0XNBgWmWekZRxnWb8irOJooJl9tO8yNhfrTMSaqlWo8w1FQDpArUrL+OGX23Zw==",
                            PhoneNumber = "01768280237",
                            PhoneNumberConfirmed = true,
                            ProfilePicture = "",
                            SecurityStamp = "cfdb5bc0-c21a-401e-bdb5-a4786ddf605c",
                            TwoFactorEnabled = false,
                            UpdateAt = new DateTime(2024, 9, 3, 9, 58, 46, 464, DateTimeKind.Local).AddTicks(8415),
                            UserName = "habibor.rahaman1010@gmail.com"
                        });
                });

            modelBuilder.Entity("Core.Entities.BlogPostTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Updated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("BlogPosts");
                });

            modelBuilder.Entity("Core.Entities.CategoryTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Core.Entities.ClassTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 9, 3, 9, 58, 46, 464, DateTimeKind.Local).AddTicks(9519),
                            ModificationDate = new DateTime(2024, 9, 3, 9, 58, 46, 464, DateTimeKind.Local).AddTicks(9520),
                            Name = "One"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 9, 3, 9, 58, 46, 464, DateTimeKind.Local).AddTicks(9522),
                            ModificationDate = new DateTime(2024, 9, 3, 9, 58, 46, 464, DateTimeKind.Local).AddTicks(9522),
                            Name = "Two"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 9, 3, 9, 58, 46, 464, DateTimeKind.Local).AddTicks(9552),
                            ModificationDate = new DateTime(2024, 9, 3, 9, 58, 46, 464, DateTimeKind.Local).AddTicks(9552),
                            Name = "Three"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 9, 3, 9, 58, 46, 464, DateTimeKind.Local).AddTicks(9553),
                            ModificationDate = new DateTime(2024, 9, 3, 9, 58, 46, 464, DateTimeKind.Local).AddTicks(9554),
                            Name = "Four"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 9, 3, 9, 58, 46, 464, DateTimeKind.Local).AddTicks(9555),
                            ModificationDate = new DateTime(2024, 9, 3, 9, 58, 46, 464, DateTimeKind.Local).AddTicks(9555),
                            Name = "Five"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 9, 3, 9, 58, 46, 464, DateTimeKind.Local).AddTicks(9557),
                            ModificationDate = new DateTime(2024, 9, 3, 9, 58, 46, 464, DateTimeKind.Local).AddTicks(9557),
                            Name = "Six"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 9, 3, 9, 58, 46, 464, DateTimeKind.Local).AddTicks(9558),
                            ModificationDate = new DateTime(2024, 9, 3, 9, 58, 46, 464, DateTimeKind.Local).AddTicks(9559),
                            Name = "Seven"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 9, 3, 9, 58, 46, 464, DateTimeKind.Local).AddTicks(9560),
                            ModificationDate = new DateTime(2024, 9, 3, 9, 58, 46, 464, DateTimeKind.Local).AddTicks(9560),
                            Name = "Eight"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 9, 3, 9, 58, 46, 464, DateTimeKind.Local).AddTicks(9561),
                            ModificationDate = new DateTime(2024, 9, 3, 9, 58, 46, 464, DateTimeKind.Local).AddTicks(9562),
                            Name = "Nine"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 9, 3, 9, 58, 46, 464, DateTimeKind.Local).AddTicks(9563),
                            ModificationDate = new DateTime(2024, 9, 3, 9, 58, 46, 464, DateTimeKind.Local).AddTicks(9563),
                            Name = "Ten"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2024, 9, 3, 9, 58, 46, 464, DateTimeKind.Local).AddTicks(9564),
                            ModificationDate = new DateTime(2024, 9, 3, 9, 58, 46, 464, DateTimeKind.Local).AddTicks(9565),
                            Name = "Colleage First Year"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2024, 9, 3, 9, 58, 46, 464, DateTimeKind.Local).AddTicks(9566),
                            ModificationDate = new DateTime(2024, 9, 3, 9, 58, 46, 464, DateTimeKind.Local).AddTicks(9566),
                            Name = "Colleg Second Year"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2024, 9, 3, 9, 58, 46, 464, DateTimeKind.Local).AddTicks(9568),
                            ModificationDate = new DateTime(2024, 9, 3, 9, 58, 46, 464, DateTimeKind.Local).AddTicks(9568),
                            Name = "BSc In CSE"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2024, 9, 3, 9, 58, 46, 464, DateTimeKind.Local).AddTicks(9569),
                            ModificationDate = new DateTime(2024, 9, 3, 9, 58, 46, 464, DateTimeKind.Local).AddTicks(9570),
                            Name = "BSc In EEE"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2024, 9, 3, 9, 58, 46, 464, DateTimeKind.Local).AddTicks(9571),
                            ModificationDate = new DateTime(2024, 9, 3, 9, 58, 46, 464, DateTimeKind.Local).AddTicks(9571),
                            Name = "BSc In CS"
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2024, 9, 3, 9, 58, 46, 464, DateTimeKind.Local).AddTicks(9572),
                            ModificationDate = new DateTime(2024, 9, 3, 9, 58, 46, 464, DateTimeKind.Local).AddTicks(9573),
                            Name = "BSc In Civil"
                        });
                });

            modelBuilder.Entity("Core.Entities.StudentTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DOB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("GETDATE()")
                        .HasAnnotation("Comment", "Date of Birth");

                    b.Property<int>("Gender")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "110b8bbf-002e-4d12-abdb-09b377339b69",
                            ConcurrencyStamp = "5f11b9db-23bf-42f1-9d97-11412a8356d3",
                            Name = "SUPERADMIN",
                            NormalizedName = "Super Admin"
                        },
                        new
                        {
                            Id = "e172b5f2-22dc-4b6e-909f-3aee39448590",
                            ConcurrencyStamp = "ce4b91ab-385c-4d20-979d-3d6234647daf",
                            Name = "ADMIN",
                            NormalizedName = "Admin"
                        },
                        new
                        {
                            Id = "983deed1-65a4-4a9d-ac53-f09d2b419df7",
                            ConcurrencyStamp = "7d8bd21b-3ca8-46d8-a9d9-9e332a5275de",
                            Name = "USER",
                            NormalizedName = "User"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "27076d17-0839-409d-8747-d078050c83ea",
                            RoleId = "110b8bbf-002e-4d12-abdb-09b377339b69"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Core.Entities.BlogPostTable", b =>
                {
                    b.HasOne("Core.Entities.CategoryTable", "Category")
                        .WithMany("BlogPosts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Core.Entities.StudentTable", b =>
                {
                    b.HasOne("Core.Entities.ClassTable", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.CategoryTable", b =>
                {
                    b.Navigation("BlogPosts");
                });

            modelBuilder.Entity("Core.Entities.ClassTable", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
